LOG_INTERVAL: 50
HOOKS:
    - "CheckpointHook"
    - "IterTimerHook"
    - "TextLoggerHook"
    - "TensorboardMetricsLogger"
    - "CocoEvaluator"
PATHS:
    TRAIN_FILE_PATTERN: "/opt/ml/input/data/tfrecord/train*"
    VAL_FILE_PATTERN: "/opt/ml/input/data/tfrecord/val*"
    WEIGHTS: "/opt/ml/input/data/weights/model.ckpt-112603"
    VAL_ANNOTATIONS: "/opt/ml/input/data/annotations/instances_val2017.json"
    OUT_DIR: "/opt/ml/checkpoints"
INPUT:
    TRAIN_BATCH_SIZE: 64
    EVAL_BATCH_SIZE: 64
MODEL:
    DENSE:
        PRE_NMS_TOP_N_TRAIN: 2000
        POST_NMS_TOP_N_TRAIN: 1000
    RCNN:
        ROI_HEAD: "StandardRoIHead"
    FRCNN:
        LOSS_TYPE: "giou"
    INFERENCE:
        VISUALIZE_INTERVAL: 500
SOLVER:
    SCHEDULE: "CosineDecay"
    OPTIMIZER: "NovoGrad"
    LR: 0.025
    BETA_1: 0.9
    BETA_2: 0.5
    MAX_ITERS: 25000
    WARMUP_STEPS: 750
    WEIGHT_DECAY: 0.0001
