LOG_INTERVAL: 200
DISTRIBUTION: 'hvd'
HOOKS: 
    - "CheckpointHook" 
    - "IterTimerHook"
    - "TextLoggerHook" 
    - "TensorboardMetricsLogger"
    - "CocoEvaluator"
    - "ImageVisualizer"
    - "GraphVisualizer"
    - "Profiler"
PATHS:
    TRAIN_FILE_PATTERN: "/opt/ml/input/data/tfrecord/train*"
    VAL_FILE_PATTERN: "/opt/ml/input/data/tfrecord/val*"
    WEIGHTS: "/opt/ml/input/data/weights/model.ckpt-112603"
    VAL_ANNOTATIONS: "/opt/ml/input/data/annotations/instances_val2017.json"
    OUT_DIR: "/opt/ml/checkpoints"
INPUT:
    TRAIN_BATCH_SIZE: 32
    EVAL_BATCH_SIZE: 32
MODEL:
    DENSE:
        PRE_NMS_TOP_N_TRAIN: 2000
        POST_NMS_TOP_N_TRAIN: 1000
    RCNN:
        ROI_HEAD: "CascadeRoIHead"
    INFERENCE:
        VISUALIZE_INTERVAL: 500
    INCLUDE_MASK: False
SOLVER:
    OPTIMIZER: "Momentum"
    LR: 0.16
    MAX_ITERS: 12000
    DECAY_STEPS:
        - 8500
        - 11000
    DECAY_LR:
        - 0.1
        - 0.01
    WARMUP_STEPS: 1000
    