LOG_INTERVAL: 50
DISTRIBUTION: 'hvd'
HOOKS: 
    - "CheckpointHook" 
    - "IterTimerHook"
    - "TextLoggerHook" 
    - "TensorboardMetricsLogger"
    - "CocoEvaluator"
    - "ImageVisualizer"
    - "GraphVisualizer"
    - "Profiler"
PATHS:
    TRAIN_FILE_PATTERN: "/opt/ml/input/data/train/train*"
    VAL_FILE_PATTERN: "/opt/ml/input/data/val/val*"
    WEIGHTS: "/opt/ml/input/data/weights/resnet/resnet-nhwc-2018-02-07/model.ckpt-112603"
    VAL_ANNOTATIONS: "/opt/ml/input/data/annotations/instances_val2017.json"
    OUT_DIR: "/opt/ml/checkpoints"
INPUT:
    TRAIN_BATCH_SIZE: 128
    EVAL_BATCH_SIZE: 128
MODEL:
    DENSE:
        PRE_NMS_TOP_N_TRAIN: 2000
        POST_NMS_TOP_N_TRAIN: 1000
    RCNN:
        ROI_HEAD: "StandardRoIHead"
    INFERENCE:
        VISUALIZE_INTERVAL: 500
    INCLUDE_MASK: False
SOLVER:
    OPTIMIZER: "Momentum"
    LR: 0.16
    MAX_ITERS: 12000
    DECAY_STEPS:
        - 9375
        - 11250
    DECAY_LR:
        - 0.1
        - 0.01
    WARMUP_STEPS: 1000
    WARM_UP_RATIO: 0.01
    