MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/opt/ml/input/data/all_data/coco/weights/resnet50.pkl"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
    INCLUDE_RPN_HEAD: True
    DONT_RECOMPUTE_SCALE_AND_BIAS: True
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TRAIN: 1000
    FPN_POST_NMS_TOP_N_PER_IMAGE: True
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  RESNETS:
    FIRST_TRANS_FUNC: "SpatialBottleneckWithFixedBatchNorm"
    TRANS_FUNC: "SpatialBottleneckWithFixedBatchNorm"
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  DALI: False
  DALI_ON_GPU: False
  CACHE_EVAL_IMAGES: True
  NUM_WORKERS: 2
  HYBRID: True
  DALI_ON_GPU: False
SOLVER:
  OPTIMIZER: "SGD"
  BASE_LR: 0.24
  WEIGHT_DECAY: 0.0001
  STEPS: (5625,7500)
  MAX_ITER: 8000
  WARMUP_FACTOR: 0.000133
  WARMUP_ITERS: 1800
  WARMUP_METHOD: "mlperf_linear"
  IMS_PER_BATCH: 256
  LR_SCHEDULE: "STEP"
TEST:
  IMS_PER_BATCH: 256
PATHS_CATALOG: "/opt/ml/code/config/paths_catalog.py"
NHWC: True
EVAL_SEGM_NUMPROCS: 10
USE_CUDA_GRAPH: True
EVAL_MASK_VIRTUAL_PASTE: True
PRECOMPUTE_RPN_CONSTANT_TENSORS: True
DTYPE: "float16"