MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/opt/ml/input/data/weights/resnet50.pkl"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
    INCLUDE_RPN_HEAD: True
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TRAIN: 12000
    FPN_POST_NMS_TOP_N_PER_IMAGE: False
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  RESNETS:
    FIRST_TRANS_FUNC: "FastBottleneckWithFixedBatchNorm"
    TRANS_FUNC: "FastBottleneckWithFixedBatchNorm"
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  DALI: False
  DALI_ON_GPU: False
  CACHE_EVAL_IMAGES: True
  NUM_WORKERS: 8
  HYBRID: True
SOLVER:
  BASE_LR: 0.12
  WEIGHT_DECAY: 0.0001
  STEPS: (12000, 16000)
  MAX_ITER: 20000
  WARMUP_FACTOR: 0.000192
  WARMUP_ITERS: 625
  WARMUP_METHOD: "mlperf_linear"
  IMS_PER_BATCH: 96
TEST:
  IMS_PER_BATCH: 48
PATHS_CATALOG: './paths_catalog_sm.py'
NHWC: True
EVAL_SEGM_NUMPROCS: 10
USE_CUDA_GRAPH: True
EVAL_MASK_VIRTUAL_PASTE: True
PRECOMPUTE_RPN_CONSTANT_TENSORS: True
DTYPE: "float16"