OUTPUT_DIR: "/opt/ml/checkpoints"
OPT_LEVEL: "O1"
HOOKS:
  - "DetectronCheckpointHook"
  - "AMP_Hook"
  - "IterTimerHook"
  - "TextLoggerHook"
  - "COCOEvaluation"
INPUT:
  TRAIN_INPUT_DIR: "/opt/ml/input/data/coco/train2017"
  VAL_INPUT_DIR: "/opt/ml/input/data/coco/val2017"
  TRAIN_ANNO_DIR: "/opt/ml/input/data/coco/annotations/instances_train2017.json"
  VAL_ANNO_DIR: "/opt/ml/input/data/coco/annotations/instances_val2017.json"
SOLVER:
  OPTIMIZER: "NovoGrad"
  BASE_LR: 0.018
  BETA1: 0.9
  BETA2: 0.4
  ALPHA: .001
  LR_SCHEDULE: "COSINE"
  IMS_PER_BATCH: 96
  WEIGHT_DECAY: 0.0005
  MAX_ITER: 16500
  WARMUP_FACTOR: .01
  WARMUP_ITERS: 625
  GRADIENT_CLIPPING: 0.0
TEST:
  IMS_PER_BATCH: 64
  PER_EPOCH_EVAL: False
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/opt/ml/input/data/weights/R-50.pkl"
  RESNETS:
    TRANS_FUNC: "BottleneckWithFixedBatchNorm"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TRAIN: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    LS: 0.1
    FPN_POST_NMS_TOP_N_PER_IMAGE: True
  ROI_HEADS:
    USE_FPN: True
    BBOX_REG_WEIGHTS: (10., 10., 5., 5.)
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    LOSS: "GIoULoss"
    DECODE: True
    CARL: True
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 4
