PATHS:
    TRAIN_FILE_PATTERN: "/opt/ml/input/data/train/train/train*"
    VAL_FILE_PATTERN: "/opt/ml/input/data/train/val/val*"
    WEIGHTS: "/opt/ml/input/data/train/model/resnet/resnet-nhwc-2018-02-07/model.ckpt-112603"
    VAL_ANNOTATIONS: "/opt/ml/input/data/train/annotations/instances_val2017.json"
    OUT_DIR: "/opt/ml/code/checkpoints/tensorflow_mask_rcnn"
INPUT:
    TRAIN_BATCH_SIZE: 384
    EVAL_BATCH_SIZE: 384
MODEL:
    DENSE:
        PRE_NMS_TOP_N_TRAIN: 2000
        POST_NMS_TOP_N_TRAIN: 1000
    RCNN:
        ROI_HEAD: "StandardRoIHead"
    FRCNN:
        LOSS_TYPE: "giou"
    INFERENCE:
        VISUALIZE_INTERVAL: 500
SOLVER:
      OPTIMIZER: "NovoGrad"
      BASE_LR: 0.042
      BETA1: 0.9
      BETA2: 0.3
      ALPHA: .001
      LR_SCHEDULE: "COSINE"
      WEIGHT_DECAY: 0.001
      MAX_ITER: 5000
      WARMUP_FACTOR: .01
      WARMUP_ITERS: 625
      GRADIENT_CLIPPING: 0.0

