CONTAINER_NAME=mlperf_training
BASE_LR=0.04
MAX_ITER=20000
WARMUP_FACTOR=0.01
WARMUP_ITERS=500
STEPS=(12000,16000)
TRAIN_IMS_PER_BATCH=16
TEST_IMS_PER_BATCH=8
FPN_POST_NMS_TOP_N_TRAIN=4000
NSOCKETS_PER_NODE=1
NCORES_PER_SOCKET=12
NPROC_PER_NODE=4
ENABLE_DALI=False
USE_CUDA_GRAPH=True
CACHE_EVAL_IMAGES=True
EVAL_SEGM_NUMPROCS=10
EVAL_MASK_VIRTUAL_PASTE=True
INCLUDE_RPN_HEAD=True
PRECOMPUTE_RPN_CONSTANT_TENSORS=True
DATALOADER_NUM_WORKERS=1
HYBRID_LOADER=True
FPN_POST_NMS_TOP_N_PER_IMAGE=False
PATHS_CATALOG=/workspace/src/paths_catalog_local.py

python -m torch.distributed.launch \
			--nnodes=1 \
			--nproc_per_node=${NPROC_PER_NODE} \
			aws_train_mlperf.py \
			--config-file 'configs/e2e_mask_rcnn_R_50_FPN_1x_1_node.yaml' \
			DTYPE 'float16' \
			DISABLE_REDUCED_LOGGING True \
			SOLVER.BASE_LR ${BASE_LR} \
			SOLVER.MAX_ITER ${MAX_ITER} \
			SOLVER.WARMUP_FACTOR ${WARMUP_FACTOR} \
			SOLVER.WARMUP_ITERS ${WARMUP_ITERS} \
			SOLVER.WARMUP_METHOD linear \
			SOLVER.STEPS ${STEPS} \
			SOLVER.IMS_PER_BATCH ${TRAIN_IMS_PER_BATCH} \
			TEST.IMS_PER_BATCH ${TEST_IMS_PER_BATCH} \
			MODEL.RPN.FPN_POST_NMS_TOP_N_TRAIN ${FPN_POST_NMS_TOP_N_TRAIN} \
			MODEL.RPN.FPN_POST_NMS_TOP_N_PER_IMAGE ${FPN_POST_NMS_TOP_N_PER_IMAGE} \
			NHWC True \
			DATALOADER.DALI ${ENABLE_DALI} \
			DATALOADER.DALI_ON_GPU ${ENABLE_DALI} \
			DATALOADER.CACHE_EVAL_IMAGES ${CACHE_EVAL_IMAGES} \
			EVAL_SEGM_NUMPROCS ${EVAL_SEGM_NUMPROCS} \
			USE_CUDA_GRAPH ${USE_CUDA_GRAPH} \
			EVAL_MASK_VIRTUAL_PASTE ${EVAL_MASK_VIRTUAL_PASTE} \
			MODEL.BACKBONE.INCLUDE_RPN_HEAD ${INCLUDE_RPN_HEAD} \
			DATALOADER.NUM_WORKERS ${DATALOADER_NUM_WORKERS} \
			PRECOMPUTE_RPN_CONSTANT_TENSORS ${PRECOMPUTE_RPN_CONSTANT_TENSORS} \
			DATALOADER.HYBRID ${HYBRID_LOADER} \
			MODEL.RESNETS.FIRST_TRANS_FUNC FastBottleneckWithFixedBatchNorm \
			MODEL.RESNETS.TRANS_FUNC FastBottleneckWithFixedBatchNorm \
			PATHS_CATALOG ${PATHS_CATALOG}